baseURL = "https://example.com/"
languageCode = "ja"
title = "枠の外ログ"
theme = "mainroad"

[params]
  description = "流れ着いて今ここ。考えすぎな私のめんどくさい日常の記録。"
  authorbox = false
  pager = true
  post_meta = ["date", "categories"]

[params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories"]

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[markup.goldmark.renderer]
  unsafe = true